name: Snake Animation

on:
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * 1"

permissions:
  contents: write

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate contribution snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: tzhengus
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
